# Generated by Django 6.0.5 on 2026-06-05 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControladorAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_ip', models.GenericIPAddressField()),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('estado_conexion', models.CharField(max_length=50)),
                ('fecha_ultimo_ping', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NivelAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_nivel', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertaSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('nivel_gravedad', models.CharField(max_length=50)),
                ('estado_atencion', models.CharField(default='Generada', max_length=50)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='accesos.controladoracceso')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioPermitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('dias_semana', models.CharField(max_length=50)),
                ('nivel_acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='accesos.nivelacceso')),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.CharField(max_length=100)),
                ('nivel_seguridad', models.CharField(max_length=50)),
                ('zona_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subzonas', to='accesos.componentezona')),
                ('nivel_acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_permitidas', to='accesos.nivelacceso')),
            ],
        ),
        migrations.CreateModel(
            name='OperadorSistema',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accesos.persona')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('turno_asignado', models.CharField(max_length=50)),
            ],
            bases=('accesos.persona',),
        ),
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_referencia', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Bloqueada', 'Bloqueada'), ('Vencida', 'Vencida')], default='Activa', max_length=20)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciales', to='accesos.persona')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('ubicacion_fisica', models.CharField(max_length=150)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_acceso', to='accesos.componentezona')),
            ],
        ),
        migrations.AddField(
            model_name='controladoracceso',
            name='punto_acceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controladores', to='accesos.puntoacceso'),
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(max_length=20)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=200, null=True)),
                ('credencial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='accesos.credencial')),
                ('dispositivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='accesos.controladoracceso')),
            ],
        ),
        migrations.CreateModel(
            name='ResolucionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_resolucion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField()),
                ('alerta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolucion', to='accesos.alertaseguridad')),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resoluciones', to='accesos.operadorsistema')),
            ],
        ),
        migrations.CreateModel(
            name='SujetoAcceso',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accesos.persona')),
                ('legajo_empleado', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('nivel_acceso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sujetos', to='accesos.nivelacceso')),
            ],
            bases=('accesos.persona',),
        ),
    ]
