# Generated by Django 6.1

import django.db.models.deletion
from django.db import migrations, models


def copiar_zonas_al_m2m(apps, schema_editor):
    Zona = apps.get_model('accesos', 'ComponenteZona')
    for zona in Zona.objects.all():
        nivel_id = getattr(zona, 'nivel_acceso_id', None)
        if not nivel_id:
            continue
        Nivel = apps.get_model('accesos', 'NivelAcceso')
        nivel = Nivel.objects.filter(pk=nivel_id).first()
        if nivel:
            nivel.zonas.add(zona)


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0002_edificio_controladoracceso_edificio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertaseguridad',
            options={'ordering': ['-fecha_hora']},
        ),
        migrations.AlterModelOptions(
            name='componentezona',
            options={'ordering': ['nombre_zona']},
        ),
        migrations.AlterModelOptions(
            name='controladoracceso',
            options={'ordering': ['numero_serie']},
        ),
        migrations.AlterModelOptions(
            name='edificio',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='nivelacceso',
            options={'ordering': ['nombre_nivel']},
        ),
        migrations.AlterModelOptions(
            name='registroacceso',
            options={'ordering': ['-fecha_hora']},
        ),
        migrations.AddField(
            model_name='componentezona',
            name='edificio',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='zonas',
                to='accesos.edificio',
            ),
        ),
        migrations.AlterField(
            model_name='componentezona',
            name='nivel_seguridad',
            field=models.CharField(default='Media', max_length=50),
        ),
        migrations.AlterField(
            model_name='controladoracceso',
            name='estado_conexion',
            field=models.CharField(default='Desconectado', max_length=50),
        ),
        migrations.AlterField(
            model_name='controladoracceso',
            name='fecha_ultimo_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credencial',
            name='tipo',
            field=models.CharField(default='RFID', max_length=50),
        ),
        migrations.AlterField(
            model_name='horariopermitido',
            name='dias_semana',
            field=models.CharField(
                help_text='Días permitidos: 0=lunes … 6=domingo, separados por coma.',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='alertaseguridad',
            name='estado_atencion',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='nivelacceso',
            name='zonas',
            field=models.ManyToManyField(
                blank=True,
                related_name='niveles',
                to='accesos.componentezona',
            ),
        ),
        migrations.RunPython(copiar_zonas_al_m2m, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='componentezona',
            name='nivel_acceso',
        ),
    ]
