# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0003_motor_reglas_zonas_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoacceso',
            name='sentido',
            field=models.CharField(
                choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')],
                default='Entrada',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='puntoacceso',
            name='tipo',
            field=models.CharField(
                choices=[('Totem', 'Tótem con cámara'), ('Lector', 'Lector de puerta')],
                default='Totem',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='puntoacceso',
            name='tiene_camara',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='sentido',
            field=models.CharField(default='Entrada', max_length=20),
        ),
        migrations.AlterField(
            model_name='credencial',
            name='tipo',
            field=models.CharField(default='Magnetica', max_length=50),
        ),
    ]
