# Generated by Django 6.1 on 2026-09-30 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0004_entrada_salida_totem'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='horas_permanencia_maxima',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.CreateModel(
            name='Presencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Dentro', 'Dentro'), ('Permanencia excedida', 'Permanencia excedida'), ('Fuera', 'Fuera')], default='Dentro', max_length=30)),
                ('ingreso', models.DateTimeField()),
                ('egreso', models.DateTimeField(blank=True, null=True)),
                ('alerta_emitida', models.BooleanField(default=False)),
                ('credencial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencias', to='accesos.credencial')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencias', to='accesos.edificio')),
                ('registro_entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencias_entrada', to='accesos.registroacceso')),
                ('registro_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencias_salida', to='accesos.registroacceso')),
                ('sujeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencias', to='accesos.sujetoacceso')),
            ],
            options={
                'ordering': ['-ingreso'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('egreso__isnull', True)), fields=('sujeto', 'edificio'), name='una_presencia_abierta_por_sujeto_edificio')],
            },
        ),
    ]
