# Generated by Django 6.1 on 2026-09-30 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0005_presencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='credencial',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credencial',
            name='motivo_estado',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='credencial',
            name='reemplaza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repuestas', to='accesos.credencial'),
        ),
        migrations.AlterField(
            model_name='credencial',
            name='estado',
            field=models.CharField(choices=[('Emitida', 'Emitida'), ('Activa', 'Activa'), ('Bloqueada', 'Bloqueada'), ('Vencida', 'Vencida'), ('Repuesta', 'Repuesta')], default='Activa', max_length=20),
        ),
        migrations.AlterField(
            model_name='credencial',
            name='tipo',
            field=models.CharField(choices=[('Peatonal', 'Peatonal'), ('Cochera', 'Cochera'), ('Magnetica', 'Magnetica')], default='Magnetica', max_length=50),
        ),
        migrations.CreateModel(
            name='MovimientoCredencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_origen', models.CharField(blank=True, max_length=20)),
                ('estado_destino', models.CharField(max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('credencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='accesos.credencial')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_credencial', to='accesos.operadorsistema')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
