# Generated by Django 6.1 on 2026-10-02 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0006_ciclo_credencial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertaseguridad',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'alerta', 'verbose_name_plural': 'alertas'},
        ),
        migrations.AlterModelOptions(
            name='componentezona',
            options={'ordering': ['nombre_zona'], 'verbose_name': 'zona', 'verbose_name_plural': 'zonas'},
        ),
        migrations.AlterModelOptions(
            name='controladoracceso',
            options={'ordering': ['numero_serie'], 'verbose_name': 'controladora', 'verbose_name_plural': 'controladoras'},
        ),
        migrations.AlterModelOptions(
            name='credencial',
            options={'verbose_name': 'llave', 'verbose_name_plural': 'llaves'},
        ),
        migrations.AlterModelOptions(
            name='edificio',
            options={'ordering': ['nombre'], 'verbose_name': 'edificio', 'verbose_name_plural': 'edificios'},
        ),
        migrations.AlterModelOptions(
            name='horariopermitido',
            options={'verbose_name': 'horario', 'verbose_name_plural': 'horarios'},
        ),
        migrations.AlterModelOptions(
            name='movimientocredencial',
            options={'ordering': ['-fecha'], 'verbose_name': 'movimiento de llave', 'verbose_name_plural': 'movimientos de llave'},
        ),
        migrations.AlterModelOptions(
            name='nivelacceso',
            options={'ordering': ['nombre_nivel'], 'verbose_name': 'nivel de acceso', 'verbose_name_plural': 'niveles de acceso'},
        ),
        migrations.AlterModelOptions(
            name='operadorsistema',
            options={'verbose_name': 'operador', 'verbose_name_plural': 'operadores'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'persona', 'verbose_name_plural': 'personas'},
        ),
        migrations.AlterModelOptions(
            name='presencia',
            options={'ordering': ['-ingreso'], 'verbose_name': 'presencia', 'verbose_name_plural': 'presencias'},
        ),
        migrations.AlterModelOptions(
            name='puntoacceso',
            options={'verbose_name': 'punto de acceso', 'verbose_name_plural': 'puntos de acceso'},
        ),
        migrations.AlterModelOptions(
            name='registroacceso',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'registro', 'verbose_name_plural': 'registros'},
        ),
        migrations.AlterModelOptions(
            name='resolucionalerta',
            options={'verbose_name': 'resolución', 'verbose_name_plural': 'resoluciones'},
        ),
        migrations.AlterModelOptions(
            name='sujetoacceso',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.CreateModel(
            name='CuentaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Operador', 'Operador'), ('Tecnico', 'Técnico')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_sistema', to='accesos.persona')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_sgca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cuenta del sistema',
                'verbose_name_plural': 'cuentas del sistema',
            },
        ),
    ]
