# Generated by Django 6.1 on 2026-10-02 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0008_migrar_operadores_a_cuentas'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenteTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('Hardware', 'Hardware'), ('Conectividad', 'Conectividad'), ('Energia', 'Energía'), ('Otro', 'Otro')], max_length=30)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Critica', 'Crítica')], default='Media', max_length=20)),
                ('estado', models.CharField(choices=[('Registrado', 'Registrado'), ('Evaluado', 'Evaluado'), ('En atencion', 'En atención'), ('Pendiente verificacion', 'Pendiente de verificación'), ('Cerrado', 'Cerrado'), ('Descartado', 'Descartado')], default='Registrado', max_length=30)),
                ('motivo_descarte', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_evaluacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('fecha_descarte', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('alerta_origen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidente_tecnico', to='accesos.alertaseguridad')),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_cerrados', to='accesos.operadorsistema')),
                ('descartado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_descartados', to='accesos.operadorsistema')),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_tecnicos', to='accesos.controladoracceso')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_tecnicos', to='accesos.edificio')),
                ('evaluado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_evaluados', to='accesos.operadorsistema')),
                ('incidente_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_posteriores', to='accesos.incidentetecnico')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_registrados', to='accesos.operadorsistema')),
            ],
            options={
                'verbose_name': 'incidente técnico',
                'verbose_name_plural': 'incidentes técnicos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='CambioEstadoIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_origen', models.CharField(blank=True, max_length=30)),
                ('estado_destino', models.CharField(max_length=30)),
                ('detalle', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_incidente', to='accesos.cuentasistema')),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado', to='accesos.incidentetecnico')),
            ],
            options={
                'verbose_name': 'cambio de estado de incidente',
                'verbose_name_plural': 'cambios de estado de incidentes',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='OrdenIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('Asignada', 'Asignada'), ('En curso', 'En curso'), ('Informada', 'Informada'), ('Verificada', 'Verificada'), ('Cancelada', 'Cancelada')], default='Asignada', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_informe', models.DateTimeField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('trabajo_realizado', models.TextField(blank=True)),
                ('resultado', models.CharField(blank=True, choices=[('solucionado', 'Solucionado'), ('parcialmente solucionado', 'Parcialmente solucionado'), ('no solucionado', 'No solucionado')], max_length=30)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('verificacion_aceptada', models.BooleanField(blank=True, null=True)),
                ('observaciones_verificacion', models.TextField(blank=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('asignada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_asignadas', to='accesos.operadorsistema')),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_canceladas', to='accesos.operadorsistema')),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='accesos.incidentetecnico')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_asignadas', to='accesos.cuentasistema')),
                ('verificada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_verificadas', to='accesos.operadorsistema')),
            ],
            options={
                'verbose_name': 'orden de intervención',
                'verbose_name_plural': 'órdenes de intervención',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reasignaciones_realizadas', to='accesos.operadorsistema')),
                ('tecnico_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_anteriores', to='accesos.cuentasistema')),
                ('tecnico_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_nuevas', to='accesos.cuentasistema')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_asignaciones', to='accesos.ordenintervencion')),
            ],
            options={
                'verbose_name': 'historial de asignación',
                'verbose_name_plural': 'historiales de asignación',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='CambioEstadoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_origen', models.CharField(blank=True, max_length=20)),
                ('estado_destino', models.CharField(max_length=20)),
                ('detalle', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_orden', to='accesos.cuentasistema')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado', to='accesos.ordenintervencion')),
            ],
            options={
                'verbose_name': 'cambio de estado de orden',
                'verbose_name_plural': 'cambios de estado de órdenes',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='incidentetecnico',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'Descartado'), _negated=True), models.Q(('motivo_descarte', ''), _negated=True), _connector='OR'), name='incidente_descartado_con_motivo'),
        ),
        migrations.AddConstraint(
            model_name='ordenintervencion',
            constraint=models.UniqueConstraint(fields=('incidente', 'numero'), name='numero_orden_unico_por_incidente'),
        ),
        migrations.AddConstraint(
            model_name='ordenintervencion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ('Asignada', 'En curso', 'Informada'))), fields=('incidente',), name='una_orden_activa_por_incidente'),
        ),
        migrations.AddConstraint(
            model_name='ordenintervencion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'Cancelada'), _negated=True), models.Q(('motivo_cancelacion', ''), _negated=True), _connector='OR'), name='orden_cancelada_con_motivo'),
        ),
    ]
